# Generated by Django 5.0.1 on 2025-12-23 10:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CostAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_index=True, max_length=255)),
                ('aggregation_level', models.CharField(choices=[('HOURLY', 'Hourly'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], max_length=10)),
                ('period_start', models.DateTimeField(db_index=True)),
                ('period_end', models.DateTimeField()),
                ('total_cost', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('total_tokens', models.PositiveBigIntegerField(default=0)),
                ('total_sessions', models.PositiveIntegerField(default=0)),
                ('avg_cost_per_session', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('avg_tokens_per_session', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('provider_breakdown', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cost_analytics',
                'ordering': ['-period_start'],
                'indexes': [models.Index(fields=['user_id', 'aggregation_level', '-period_start'], name='cost_analyt_user_id_9619f9_idx'), models.Index(fields=['period_start', 'period_end'], name='cost_analyt_period__daaed4_idx')],
                'unique_together': {('user_id', 'aggregation_level', 'period_start')},
            },
        ),
        migrations.CreateModel(
            name='CostBudget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_index=True, max_length=255)),
                ('budget_limit', models.DecimalField(decimal_places=4, help_text='Budget limit in USD', max_digits=10)),
                ('period', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], default='MONTHLY', max_length=10)),
                ('current_usage', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('warning_threshold', models.DecimalField(decimal_places=2, default=80.0, help_text='Percentage of budget at which to send warning (0-100)', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_start', models.DateTimeField(help_text='Start of current budget period')),
                ('period_end', models.DateTimeField(help_text='End of current budget period')),
            ],
            options={
                'db_table': 'cost_budgets',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id', 'is_active'], name='cost_budget_user_id_469b0b_idx'), models.Index(fields=['period_end'], name='cost_budget_period__ac2c10_idx')],
                'unique_together': {('user_id', 'period', 'is_active')},
            },
        ),
        migrations.CreateModel(
            name='CostAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_index=True, max_length=255)),
                ('alert_type', models.CharField(choices=[('WARNING', 'Budget Warning'), ('LIMIT_EXCEEDED', 'Budget Limit Exceeded'), ('UNUSUAL_USAGE', 'Unusual Usage Pattern'), ('DAILY_SUMMARY', 'Daily Usage Summary')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('DISMISSED', 'Dismissed')], default='PENDING', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict, help_text='Additional alert data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('budget', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='costs.costbudget')),
            ],
            options={
                'db_table': 'cost_alerts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id', '-created_at'], name='cost_alerts_user_id_44f0da_idx'), models.Index(fields=['status', '-created_at'], name='cost_alerts_status_86fd98_idx'), models.Index(fields=['alert_type', '-created_at'], name='cost_alerts_alert_t_b1b960_idx')],
            },
        ),
    ]
