# Generated by Django 5.0.1 on 2025-12-23 10:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_index=True, help_text='User identifier for the research session', max_length=255)),
                ('query', models.TextField(help_text='Original research query submitted by user')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('report', models.JSONField(blank=True, help_text='Final structured research report', null=True)),
                ('summary', models.TextField(blank=True, help_text='Brief summary of research findings')),
                ('reasoning', models.JSONField(blank=True, help_text='High-level reasoning and methodology used', null=True)),
                ('langsmith_trace_id', models.CharField(blank=True, db_index=True, help_text='LangSmith trace ID for debugging and observability', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_session', models.ForeignKey(blank=True, help_text='Parent research session if this is a continuation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_sessions', to='research.researchsession')),
            ],
            options={
                'db_table': 'research_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResearchFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(help_text='Original filename', max_length=255)),
                ('file_type', models.CharField(choices=[('PDF', 'PDF Document'), ('TXT', 'Text File'), ('DOC', 'Word Document'), ('DOCX', 'Word Document (DOCX)')], help_text='Type of uploaded file', max_length=10)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('content_summary', models.TextField(blank=True, help_text='AI-generated summary of file content')),
                ('file_path', models.CharField(help_text='Path to stored file', max_length=500)),
                ('is_processed', models.BooleanField(default=False, help_text='Whether file content has been extracted and summarized')),
                ('processing_error', models.TextField(blank=True, help_text='Error message if processing failed')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(help_text='Research session this file belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='files', to='research.researchsession')),
            ],
            options={
                'db_table': 'research_files',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ResearchCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_tokens', models.PositiveIntegerField(default=0, help_text='Number of input tokens used')),
                ('output_tokens', models.PositiveIntegerField(default=0, help_text='Number of output tokens generated')),
                ('total_tokens', models.PositiveIntegerField(default=0, help_text='Total tokens (input + output)')),
                ('estimated_cost', models.DecimalField(decimal_places=4, default=0.0, help_text='Estimated cost in USD', max_digits=10)),
                ('provider_costs', models.JSONField(blank=True, default=dict, help_text='Detailed cost breakdown by provider (OpenAI, Anthropic, etc.)')),
                ('currency', models.CharField(default='USD', help_text='Currency for cost calculations', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(help_text='Research session this cost data belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='cost', to='research.researchsession')),
            ],
            options={
                'db_table': 'research_costs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='researchsession',
            index=models.Index(fields=['user_id', '-created_at'], name='research_se_user_id_5919ac_idx'),
        ),
        migrations.AddIndex(
            model_name='researchsession',
            index=models.Index(fields=['status', '-created_at'], name='research_se_status_aad02f_idx'),
        ),
        migrations.AddIndex(
            model_name='researchsession',
            index=models.Index(fields=['parent_session', '-created_at'], name='research_se_parent__ee35f9_idx'),
        ),
        migrations.AddIndex(
            model_name='researchfile',
            index=models.Index(fields=['session', '-uploaded_at'], name='research_fi_session_c59409_idx'),
        ),
        migrations.AddIndex(
            model_name='researchfile',
            index=models.Index(fields=['file_type', '-uploaded_at'], name='research_fi_file_ty_99db8d_idx'),
        ),
        migrations.AddIndex(
            model_name='researchfile',
            index=models.Index(fields=['is_processed'], name='research_fi_is_proc_20aeb2_idx'),
        ),
        migrations.AddIndex(
            model_name='researchcost',
            index=models.Index(fields=['session'], name='research_co_session_4bca7f_idx'),
        ),
        migrations.AddIndex(
            model_name='researchcost',
            index=models.Index(fields=['-estimated_cost'], name='research_co_estimat_db967e_idx'),
        ),
        migrations.AddIndex(
            model_name='researchcost',
            index=models.Index(fields=['-total_tokens'], name='research_co_total_t_1005b0_idx'),
        ),
    ]
