# Generated by Django 5.0.1 on 2025-12-23 10:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileProcessingJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_id', models.UUIDField(help_text='ID of the ResearchFile being processed')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('task_id', models.CharField(blank=True, help_text='Celery task ID', max_length=255, null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if processing failed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'file_processing_jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['file_id'], name='file_proces_file_id_39d48f_idx'), models.Index(fields=['status', '-created_at'], name='file_proces_status_cb75e5_idx'), models.Index(fields=['task_id'], name='file_proces_task_id_d0aa4b_idx')],
            },
        ),
        migrations.CreateModel(
            name='FileUploadSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('research_session_id', models.UUIDField(help_text='ID of the associated research session')),
                ('user_id', models.CharField(db_index=True, max_length=255)),
                ('total_files', models.PositiveIntegerField(default=0)),
                ('processed_files', models.PositiveIntegerField(default=0)),
                ('failed_files', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'file_upload_sessions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['research_session_id'], name='file_upload_researc_a4a6bf_idx'), models.Index(fields=['user_id', '-created_at'], name='file_upload_user_id_796185_idx')],
            },
        ),
    ]
